# Generated by Django 6.0.1 on 2026-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_storage',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'S3/R2')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='local_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
